security:
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
    encoders: 
        Bookstore\BookBundle\Entity\User: bcrypt
    providers:
        db_users:
            entity: { class: BookstoreBundle:User, property: username}

    firewalls:
        secured_area:
            pattern: ^/
            form_login: 
                use_referer: true
            logout: 
                path: logout
                target: display_books
            anonymous: ~
            #http_basic:
                #realm: "Secured Demo Area"
    access_control:
       # - { path: ^/cart, roles: ROLE_USER }
       # - { path: ^/user, roles: ROLE_USER }