security:
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
    encoders: 
        #Bookstore\BookBundle\Entity\User: bcrypt
        Bookstore\BookBundle\Entity\User: 
            algorithm: sha1
            encode_as_base64: false
            iterations: 1
    providers:
        db_users:
            entity: { class: BookstoreBundle:User, property: username}

    firewalls:
        secured_area:
            pattern: ^/
            form_login: 
                use_referer: true
            logout: 
                path: logout
                target: display_books
            anonymous: ~
            
        cart:
            pattern: ^/cart
            form_login:
                login_path: login
                check_path: login_check
                #use_referer: true
            logout: 
                path: /logout
                target: display_books
            anonymous: ~
            #http_basic:
                #realm: "Secured Demo Area"
    access_control:
       # - { path: ^/cart, roles: ROLE_USER }
       # - { path: ^/user, roles: ROLE_USER }