bookstore_homepage:
    path:     /
    defaults: { _controller: BookstoreBundle:Book:index }
    
display_books:
    pattern: /book/browse
    defaults: { _controller: BookstoreBundle:Book:browse }
    
search:
    pattern: /book/search
    defaults: { _controller: BookstoreBundle:Book:search }
    
details_books:
    pattern: /book/details/{id}
    defaults: { _controller: BookstoreBundle:Book:details }
    requirements:
        id: \d+
        
rate_books:
    pattern: /book/rate
    defaults: { _controller: BookstoreBundle:Book:rate }
    
create_user:
    pattern: /user/create
    defaults: { _controller: BookstoreBundle:User:create }
    
edit_user:
    pattern: /user/edit/{id}
    defaults: { _controller: BookstoreBundle:User:edit }
    
user_login:
    pattern: /user/login
    defaults: { _controller: BookstoreBundle:User:login }
    
    
login:
    pattern: /login
    defaults: { _controller: BookstoreBundle:Security:login }
login_check:
    pattern: /login_check
    #dont need defaults as the security component will intercept this
logout:
    pattern: /logout
    #again, security component will intercept so no defaults
account:
    pattern: /account/{id}
    defaults: { _controller: BookstoreBundle:Security:account }
    requirements:
        id: \d+
account_change:
    pattern: /account/{id}/submit
    defaults: { _controller: BookstoreBundle:Security:account_change }
    requirements:
        id: \d+    
    
    
cart_add:
    pattern: /cart/add/{bid}
    defaults: { _controller: BookstoreBundle:Cart:add }
    requirements:
        bid: \d+
    
cart_delete:
    pattern: /cart/delete/{id}
    defaults: { _controller: BookstoreBundle:Cart:delete }
    
view_cart:
    pattern: /cart/view
    defaults: { _controller: BookstoreBundle:Cart:view }
    
cart_buy:
    pattern: /cart/buy
    defaults: { _controller: BookstoreBundle:Cart:buy }  
    
update_cart:
    path: /cart/update
    defaults: { _controller: BookstoreBundle:Cart:update }