bookstore_homepage:
    path:     /
    defaults: { _controller: BookstoreBundle:Book:index }
    
display_books:
    pattern: /book/browse
    defaults: { _controller: BookstoreBundle:Book:browse }
    
search:
    pattern: /book/search
    defaults: { _controller: BookstoreBundle:Book:search }
    
details_books:
    pattern: /book/details/{id}
    defaults: { _controller: BookstoreBundle:Book:details }
    requirements:
        id: \d+
        
rate_books:
    pattern: /book/rate
    defaults: { _controller: BookstoreBundle:Book:rate }
    
register:
    pattern: /account/register
    defaults: { _controller: BookstoreBundle:Security:register }
    
addAccount:
    pattern: /account/add
    defaults: { _controller: BookstoreBundle:Security:addAccount }    
edit_user:
    pattern: /user/edit/{id}
    defaults: { _controller: BookstoreBundle:User:edit }
    
user_login:
    pattern: /user/login
    defaults: { _controller: BookstoreBundle:User:login }
    
    
login:
    pattern: /login
    defaults: { _controller: BookstoreBundle:Security:login }
login_check:
    pattern: /login_check
    #dont need defaults as the security component will intercept this
logout:
    pattern: /logout
    #again, security component will intercept so no defaults
account:
    pattern: /account/{id}
    defaults: { _controller: BookstoreBundle:Security:account }
    requirements:
        id: \d+
account_change:
    pattern: /account/{id}/submit
    defaults: { _controller: BookstoreBundle:Security:account_change }
    requirements:
        id: \d+    
    
    
cart_add:
    pattern: /cart/add/{bid}
    defaults: { _controller: BookstoreBundle:Cart:add }
    requirements:
        bid: \d+
    
cart_delete:
    pattern: /cart/delete/{id}
    defaults: { _controller: BookstoreBundle:Cart:delete }
    
view_cart:
    pattern: /cart/view
    defaults: { _controller: BookstoreBundle:Cart:view }
    
purchase:
    pattern: /cart/buy
    defaults: { _controller: BookstoreBundle:Cart:purchase }  
    
update_cart:
    path: /cart/update
    defaults: { _controller: BookstoreBundle:Cart:update }
    
rate_form:
    pattern: /rate/{id}
    defaults: { _controller: BookstoreBundle:Book:rate } 